name: Porfolio
favicon: null
layout_spectrum: 0.49722
typography_spectrum: 0.9924015023279935
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#86cfbb'
    - '#19410f'
    - '#f60341'
    - '#f7b263'
    - '#fc4494'
  brandStrength: 0
  lightness: 0.28102666418999434
  saturation: 0.14026067312806845
  rhythmicContrast: 0.0272204561624676
purpose: []
